#!/bin/sh
set -e

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if which update-grub2 > /dev/null ; then
        update-grub2 || true
    fi
fi

